### ISSUE TITLE
Can you provide a description and info also on the top?

### ISSUE THREAD

**Issue by SamiSha99** [haithhawk/mashrou_cheetah#30]
To make it easier for people to go the site quicker instead of reading the README.md

http://i.prntscr.com/e6mvp5mBRJiukuRZDp_cZQ.png

**Comment by NickP123** [comment]
Hey Sami. Yes I wanted to do so. Thanks.  As it was hosted on Haithem's repository I didn't have the access rights. Can update that now.

**Comment by SamiSha99** [comment]
Thanks for the response.
