### ISSUE TITLE
router.js structure

### ISSUE THREAD

**Issue by shiryz** [haithhawk/mashrou_cheetah#33]
You've written your router with if and else if, for readability and easier maintenance, it's better to use a map on top so you map a url to a file path, if you don't like map, then use a switch statement.
The use of any of the above makes a lot easier to add a route in the future and will make it easier to understand which routes you have :train2:. 
(https://github.com/haithhawk/mashrou_cheetah/blob/master/src/router.js#L9)

**Comment by ghassanmas** [comment]
@shiryz Resolved
