### ISSUE TITLE
For loop in apiHandler

### ISSUE THREAD

**Issue by finnhodgkin** [haithhawk/mashrou_cheetah#40]
Is there a reason you're using a for loop in the `apiHandler`? For clarity I would use both destructuring _and_ an array method like reduce. Something like this (untested): 

```js
const { articles } = JSON.parse(body);
const resultNews = articles.reduce((articlesResult, article) => {
  const {
    description, urlToImage, title, url,
  } = article;

  if (description && urlToImage) {
    articlesResult.concat({
      title,
      description,
      url,
      urlImage: urlToImage,
    });
  }

  return articlesResult;
}, []);
```

**Comment by ghassanmas** [comment]
Looks like your example above seems a legit replacement, The only thing is in your example you are still forced to use the original object keys names.

**Comment by finnhodgkin** [comment]
I address that with the final property - `urlToImage` is assigned to the key `urlImage`.

**Comment by ghassanmas** [comment]
Yup, got that. Worked well for articlesResult.push but for concat, returned empty array

**Comment by finnhodgkin** [comment]
Lol yeah I forgot to return the concat... Knew I should've run the code before posting.

```js
const resultNews = articles.reduce((articlesResult, article) => {
    const {
      description, urlToImage, title, url,
    } = article;

    return description && urlToImage
      ? articlesResult.concat({
        title,
        description,
        url,
        urlImage: urlToImage,
      })
      : articlesResult;
  }, []);
```

Push is evil :smiling_imp:

**Comment by ghassanmas** [comment]
Oh so I got it now, so concat create new array, it doesn't miss with the original array!

**Comment by finnhodgkin** [comment]
Yeah exactly

**Comment by ghassanmas** [comment]
@finnhodgkin Resolved
